


export enum MessagesModal {

    RECORD_SAVED="RECORD_SAVED",
    RECORD_DELETED="RECORD_DELETED",
    RECORD_UPDATE="RECORD_UPDATE",
    QUESTION_DELETE="QUESTION_DELETE",
    QUESTION_CHANGE_CONFIG_COMPETENCY="QUESTION_CHANGE_CONFIG_COMPETENCY",
    QUESTION_DISABLE="QUESTION_DISABLE",
    QUESTION_LOGOUT="QUESTION_LOGOUT",
    SESSION_EXPIRED="SESSION_EXPIRED",
    CONNECTION_PROBLEM="CONNECTION_PROBLEM",

}
 
 